# 此为精简配置，如需更为详细的配置，可参考 https://wiki.metacubex.one/config
# 如不会配置，也可自行寻找懒人配置，例如(Surfing 模块配置)：https://raw.githubusercontent.com/GitMetaio/Surfing/refs/heads/main/box_bll/clash/config.yaml

proxy-providers:
  proxy1:
    type: http
    url: "https://api.wd-purple.com/sub?target=clash&emoji=true&udp=true&scv=true&new_name=true&filename=WestData&url=https%3A%2F%2Fwd-purple.com%2Fsubscribe%2Febrbxg-4_sicrmf-lefgnzsf"
    path: ./proxy_provider/proxy1.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://cp.cloudflare.com
      interval: 300
      timeout: 1000
      tolerance: 100
  # 多订阅按照下面照葫芦画瓢即可
  # proxy2:
  #   type: http
  #   url: "填写订阅链接"
  #   path: ./proxy_provider/proxy2.yaml
  #   interval: 3600
  #   health-check:
  #     enable: true
  #     url: https://cp.cloudflare.com
  #     interval: 300
  #     timeout: 1000
  #     tolerance: 100

mixed-port: 7890
redir-port: 9797
tproxy-port: 9898
mode: Rule
bind-address: '*'
ipv6: true
allow-lan: true
unified-delay: true
tcp-concurrent: true
log-level: error
find-process-mode: always
global-client-fingerprint: random
external-controller: 0.0.0.0:9090
external-ui: ./dashboard

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]

tun:
  exclude-uid: []
  enable: true
  device: meta
  stack: mixed
  dns-hijack: [any:53, tcp://any:53]
  udp-timeout: 300
  auto-route: true
  auto-redirect: false
  auto-detect-interface: true
  strict-route: false

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "rule-set:Fake-IP-Filter"
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  nameserver-policy:
    "rule-set:cn_domain":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
  nameserver:
    - tls://8.8.4.4
    - tls://1.1.1.1

proxies:
  - {name: DNS_Hijack, type: dns}

proxy-groups:
  - name: 国外代理
    type: select
    exclude-type: "dns"
    icon: https://ghfast.top/raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Proxy.png
    proxies:
      - ALL·狮城地区
      - ALL·中国台湾
      - ALL·香港地区
      - ALL·日本地区      
      - ALL·美国地区
      - ALL·其它地区
  
  - name: ALL·日本地区
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@rm/Home/icon/JP.svg"
    filter: "^(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)).*$"
    type: url-test
    include-all: true
    interval: 300
    lazy: true
    timeout: 3000
    max-failed-times: 5
    expected-status: 204
    url: 'https://www.gstatic.com/generate_204'

  - name: ALL·中国台湾
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@rm/Home/icon/CN.svg"
    filter: "^(?=.*(台|新北|彰化|TW|Taiwan|taipei)).*$"
    type: url-test
    include-all: true
    interval: 300
    lazy: true
    timeout: 3000
    max-failed-times: 5
    expected-status: 204
    url: 'https://www.gstatic.com/generate_204'

  - name: ALL·香港地区
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@rm/Home/icon/HK.svg"
    filter: "^(?=.*(港|HK|hk|Hong Kong|HongKong|hongkong)).*$"
    type: url-test
    include-all: true
    interval: 300
    lazy: true
    timeout: 3000
    max-failed-times: 5
    expected-status: 204
    url: 'https://www.gstatic.com/generate_204'

  - name: ALL·美国地区
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@rm/Home/icon/US.svg"
    filter: "^(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)).*$"
    type: url-test
    include-all: true
    interval: 300
    lazy: true
    timeout: 3000
    max-failed-times: 5
    expected-status: 204
    url: 'https://www.gstatic.com/generate_204'

  - name: ALL·狮城地区
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@rm/Home/icon/Singapore.svg"
    filter: "^(?=.*(新加坡|坡|狮城|SG|Singapore)).*$"
    type: url-test
    include-all: true
    interval: 300
    lazy: true
    timeout: 3000
    max-failed-times: 5
    expected-status: 204
    url: 'https://www.gstatic.com/generate_204'

  - name: ALL·其它地区
    icon: "https://cdn.jsdelivr.net/gh/GitMetaio/Surfing@rm/Home/icon/Globe.svg"
    filter: "^(?!.*(港|HK|hk|Hong Kong|HongKong|hongkong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|台|新北|彰化|TW|Taiwan|新加坡|坡|狮城|SG|Singapore|灾|网易|Netease|套餐|重置|剩余|到期|订阅|群|账户|流量|有效期|时间|官网|拒绝|DNS|Ch|网址|售|防失)).*$"
    type: url-test
    include-all: true
    interval: 300
    lazy: true
    timeout: 3000
    max-failed-times: 5
    expected-status: 204
    url: 'https://www.gstatic.com/generate_204'

  - name: 国内直连
    type: select
    proxies: [DIRECT]
    include-all: true
    exclude-type: "dns"
    icon: https://ghfast.top/raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/China.png

  - name: 漏网之鱼
    type: select
    proxies: [国外代理,国内直连]
    icon: https://ghfast.top/raw.githubusercontent.com/Koolson/Qure/refs/heads/master/IconSet/Color/Final.png

rule-providers:
  Fake-IP-Filter:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    path: ./rule_provider/Fake-IP-Filter.mrs
    url: "https://ghfast.top/github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/fakeip-filter.mrs"
    proxy: DIRECT
  proxy_domain:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    path: ./rule_provider/proxy_domain.mrs
    url: "https://ghfast.top/github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/proxy.mrs"
    proxy: DIRECT
  cn_ip:
    type: http
    behavior: ipcidr
    format: mrs
    interval: 86400
    path: ./rule_provider/cn_ip.mrs
    url: "https://ghfast.top/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cn.mrs"
    proxy: DIRECT
  private_ip:
    type: http
    behavior: ipcidr
    format: mrs
    interval: 86400
    path: ./rule_provider/private_ip.mrs
    url: "https://ghfast.top/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/private.mrs"
    proxy: DIRECT
  cn_domain:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    path: ./rule_provider/cn_domain.mrs
    url: "https://ghfast.top/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/cn.mrs"
    proxy: DIRECT
  private_domain:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    path: ./rule_provider/private_domain.mrs
    url: "https://ghfast.top/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/private.mrs"
    proxy: DIRECT
  
rules:
  - DST-PORT,53,DNS_Hijack
  - RULE-SET,proxy_domain,国外代理
  - OR,((RULE-SET,cn_ip),(RULE-SET,cn_domain),(RULE-SET,private_ip),(RULE-SET,private_domain)),国内直连
  - MATCH,漏网之鱼